// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4915.ArcadeDriveRobot.commands;
import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class AutonomousLowGoal extends CommandGroup {
    
    public  AutonomousLowGoal() {
        addParallel(new HarvesterWheelsDefault());
        addParallel(new StopWindingMotor());
        addSequential(new DriveBackwards());
        addParallel(new StopDriveTrain());
        addSequential(new Wait());
        addSequential(new IntakeRelease());
        
        System.out.println("Autononmous Low Goal Ended");
    }
}
